#ifndef _BL702_ROMDRIVER_H_
#define _BL702_ROMDRIVER_H_

#include <stdint.h>

#define ROMAPI_INDEX_SECT_SIZE     (0x800)
#define ROMAPI_INDEX_MAX           (ROMAPI_INDEX_SECT_SIZE / 4 - 1)

typedef enum {
    ROM_API_INDEX_VERSION = 0,
    ROM_API_INDEX_RSVD_0,
    ROM_API_INDEX_RSVD_1,
    ROM_API_INDEX_RSVD_LAST,


    ROM_API_INDEX_AON_Power_On_MBG,
    ROM_API_INDEX_AON_Power_Off_MBG,
    ROM_API_INDEX_AON_Power_On_XTAL,
    ROM_API_INDEX_AON_Set_Xtal_CapCode,
    ROM_API_INDEX_AON_Get_Xtal_CapCode,
    ROM_API_INDEX_AON_Set_Xtal_CapCode_Extra,
    ROM_API_INDEX_AON_Power_Off_XTAL,
    ROM_API_INDEX_AON_Power_On_BG,
    ROM_API_INDEX_AON_Power_Off_BG,
    ROM_API_INDEX_AON_Power_On_LDO11_SOC,
    ROM_API_INDEX_AON_Power_Off_LDO11_SOC,
    ROM_API_INDEX_AON_Power_On_SFReg,
    ROM_API_INDEX_AON_Power_Off_SFReg,
    ROM_API_INDEX_AON_Set_LDO11_SOC_Sstart_Delay,
    ROM_API_INDEX_AON_Set_DCDC14_Top_0,
    ROM_API_INDEX_AON_Trim_Ldo11socVoutTrim,
    ROM_API_INDEX_AON_Trim_Ldo14VoutTrim,
    ROM_API_INDEX_AON_Trim_Dcdc14VoutTrim,

    ROM_API_INDEX_Clock_System_Clock_Get,
    ROM_API_INDEX_Clock_Peripheral_Clock_Get,

    ROM_API_INDEX_SystemCoreClockGet,

    ROM_API_INDEX_CPU_Get_MTimer_Clock,
    ROM_API_INDEX_CPU_Get_MTimer_Counter,
    ROM_API_INDEX_CPU_Get_CPU_Cycle,
    ROM_API_INDEX_CPU_Get_MTimer_US,
    ROM_API_INDEX_CPU_Get_MTimer_MS,
    ROM_API_INDEX_CPU_MTimer_Delay_US,
    ROM_API_INDEX_CPU_MTimer_Delay_MS,

    ROM_API_INDEX_BL702L_Delay_US,
    ROM_API_INDEX_BL702L_Delay_MS,

    ROM_API_INDEX_EF_Ctrl_Get_Trim_Parity,
    ROM_API_INDEX_EF_Ctrl_Read_Common_Trim,
    ROM_API_INDEX_EF_Ctrl_Write_Common_Trim,
    ROM_API_INDEX_EF_Ctrl_Is_MAC_Address_Slot_Empty,
    ROM_API_INDEX_EF_Ctrl_Write_MAC_Address_Opt,
    ROM_API_INDEX_EF_Ctrl_Read_MAC_Address_Opt,
    ROM_API_INDEX_EF_Ctrl_Sw_AHB_Clk_0,
    ROM_API_INDEX_EF_Ctrl_Program_Efuse_0,
    ROM_API_INDEX_EF_Ctrl_Load_Efuse_R0,
    ROM_API_INDEX_EF_Ctrl_Busy,
    ROM_API_INDEX_EF_Ctrl_AutoLoad_Done,
    ROM_API_INDEX_EF_Ctrl_Write_Dbg_Pwd,
    ROM_API_INDEX_EF_Ctrl_Read_Dbg_Pwd,
    ROM_API_INDEX_EF_Ctrl_Readlock_Dbg_Pwd,
    ROM_API_INDEX_EF_Ctrl_Writelock_Dbg_Pwd,
    ROM_API_INDEX_EF_Ctrl_Write_Secure_Cfg,
    ROM_API_INDEX_EF_Ctrl_Read_Secure_Cfg,
    ROM_API_INDEX_EF_Ctrl_Write_Secure_Boot,
    ROM_API_INDEX_EF_Ctrl_Read_Secure_Boot,
    ROM_API_INDEX_EF_Ctrl_Write_Sw_Usage,
    ROM_API_INDEX_EF_Ctrl_Read_Sw_Usage,
    ROM_API_INDEX_EF_Ctrl_Writelock_Sw_Usage,
    ROM_API_INDEX_EF_Ctrl_Write_MAC_Address,
    ROM_API_INDEX_EF_Ctrl_Get_Byte_Zero_Cnt,
    ROM_API_INDEX_EF_Ctrl_Is_All_Bits_Zero,
    ROM_API_INDEX_EF_Ctrl_Read_MAC_Address,
    ROM_API_INDEX_EF_Ctrl_Writelock_MAC_Address,
    ROM_API_INDEX_EF_Ctrl_Read_Chip_ID,
    ROM_API_INDEX_EF_Ctrl_Read_Device_Info,
    ROM_API_INDEX_EF_Ctrl_Is_CapCode_Empty,
    ROM_API_INDEX_EF_Ctrl_Write_CapCode_Opt,
    ROM_API_INDEX_EF_Ctrl_Read_CapCode_Opt,
    ROM_API_INDEX_EF_Ctrl_Is_PowerOffset_Slot_Empty,
    ROM_API_INDEX_EF_Ctrl_Write_PowerOffset_Opt,
    ROM_API_INDEX_EF_Ctrl_Read_PowerOffset_Opt,
    ROM_API_INDEX_EF_Ctrl_Write_AES_Key,
    ROM_API_INDEX_EF_Ctrl_Read_AES_Key,
    ROM_API_INDEX_EF_Ctrl_Writelock_AES_Key,
    ROM_API_INDEX_EF_Ctrl_Readlock_AES_Key,
    ROM_API_INDEX_EF_Ctrl_Program_Direct_R0,
    ROM_API_INDEX_EF_Ctrl_Read_Direct_R0,
    ROM_API_INDEX_EF_Ctrl_Clear,
    ROM_API_INDEX_EF_Ctrl_Crc_Enable,
    ROM_API_INDEX_EF_Ctrl_Crc_Is_Busy,
    ROM_API_INDEX_EF_Ctrl_Crc_Set_Golden,
    ROM_API_INDEX_EF_Ctrl_Crc_Result,

    ROM_API_INDEX_GLB_Get_Root_CLK_Sel,
    ROM_API_INDEX_GLB_Set_System_CLK_Div,
    ROM_API_INDEX_GLB_Get_BCLK_Div,
    ROM_API_INDEX_GLB_Get_HCLK_Div,
    ROM_API_INDEX_GLB_Set_System_CLK,

    ROM_API_INDEX_System_Core_Clock_Update_From_RC32M,

    ROM_API_INDEX_GLB_Set_MAC154_ZIGBEE_CLK,
    ROM_API_INDEX_GLB_Set_BLE_CLK,
    ROM_API_INDEX_GLB_Set_AUDIO_CLK,
    ROM_API_INDEX_GLB_Set_KYS_CLK,
    ROM_API_INDEX_GLB_Set_DMA_CLK,
    ROM_API_INDEX_GLB_Set_IR_CLK,
    ROM_API_INDEX_GLB_Set_SF_CLK,
    ROM_API_INDEX_GLB_Set_UART_CLK,
    ROM_API_INDEX_GLB_Sel_TMR_GPIO_Clock,
    ROM_API_INDEX_GLB_Set_Chip_Out_0_CLK_Sel,
    ROM_API_INDEX_GLB_Set_Chip_Out_1_CLK_Sel,
    ROM_API_INDEX_GLB_Set_Chip_Out_0_CLK_Enable,
    ROM_API_INDEX_GLB_Set_Chip_Out_1_CLK_Enable,
    ROM_API_INDEX_GLB_Set_I2C_CLK,
    ROM_API_INDEX_GLB_Set_SPI_CLK,
    ROM_API_INDEX_GLB_Set_PKA_CLK_Sel,
    ROM_API_INDEX_GLB_SW_System_Reset,
    ROM_API_INDEX_GLB_SW_CPU_Reset,
    ROM_API_INDEX_GLB_SW_POR_Reset,
    ROM_API_INDEX_GLB_AHB_MCU_Software_Reset,
    ROM_API_INDEX_GLB_Disrst_Set,
    ROM_API_INDEX_GLB_MAC154_ZIGBEE_Reset,
    ROM_API_INDEX_GLB_BLE_Reset,
    ROM_API_INDEX_GLB_PER_Clock_Gate,
    ROM_API_INDEX_GLB_PER_Clock_UnGate,
    ROM_API_INDEX_GLB_Set_RTC_Mode,
    ROM_API_INDEX_GLB_BMX_Init,
    ROM_API_INDEX_GLB_BMX_Addr_Monitor_Enable,
    ROM_API_INDEX_GLB_BMX_Addr_Monitor_Disable,
    ROM_API_INDEX_GLB_BMX_BusErrResponse_Enable,
    ROM_API_INDEX_GLB_BMX_BusErrResponse_Disable,
    ROM_API_INDEX_GLB_BMX_Get_Status,
    ROM_API_INDEX_GLB_BMX_Get_Err_Addr,
    ROM_API_INDEX_GLB_BMX_BusErrClr_Set,
    ROM_API_INDEX_GLB_Set_SRAM_PARM,
    ROM_API_INDEX_GLB_Get_SRAM_PARM,
    ROM_API_INDEX_GLB_Set_OCRAM_PARM,
    ROM_API_INDEX_GLB_Get_OCRAM_PARM,
    ROM_API_INDEX_GLB_Set_EM_Sel,
    ROM_API_INDEX_GLB_Set_Kys_Drv_Col,
    ROM_API_INDEX_GLB_GPIO_O_Latch_Mode_Set,
    ROM_API_INDEX_GLB_JTAG_Sig_Swap_Set,
    ROM_API_INDEX_GLB_CCI_Use_IO_0_1_2_7,
    ROM_API_INDEX_GLB_CCI_Use_Jtag_Pin,
    ROM_API_INDEX_GLB_Swap_SPI_0_MOSI_With_MISO,
    ROM_API_INDEX_GLB_Set_SPI_0_ACT_MOD_Sel,
    ROM_API_INDEX_GLB_Set_Flash_Scenario,
    ROM_API_INDEX_GLB_Set_Embedded_FLash_IO_PARM,
    ROM_API_INDEX_GLB_Set_MTimer_CLK,
    ROM_API_INDEX_GLB_Set_ADC_CLK,
    ROM_API_INDEX_GLB_Set_DIG_32K_CLK,
    ROM_API_INDEX_GLB_SW_BLE_WAKEUP_REQ_Set,
    ROM_API_INDEX_GLB_UART_Fun_Sel,
    ROM_API_INDEX_GLB_Power_Off_DLL,
    ROM_API_INDEX_GLB_Power_On_DLL,
    ROM_API_INDEX_GLB_Enable_DLL_All_Clks,
    ROM_API_INDEX_GLB_Enable_DLL_Clk,
    ROM_API_INDEX_GLB_Disable_DLL_All_Clks,
    ROM_API_INDEX_GLB_Disable_DLL_Clk,
    ROM_API_INDEX_GLB_Set_Flash_Id_Value,
    ROM_API_INDEX_GLB_Get_Flash_Id_Value,
    ROM_API_INDEX_GLB_Trim_RC32M,
    ROM_API_INDEX_GLB_Set_Xtal_Cnt32k_Process,
    ROM_API_INDEX_GLB_Clear_Xtal_Cnt32k_Done,
    ROM_API_INDEX_GLB_RC32K_Deg_Start,
    ROM_API_INDEX_GLB_RC32K_Deg_End,
    ROM_API_INDEX_GLB_RC32K_Deg_Enable,
    ROM_API_INDEX_GLB_Xtal_Deg_Cnt_Limit_Set,
    ROM_API_INDEX_GLB_IR_LED_Driver_Enable,
    ROM_API_INDEX_GLB_IR_LED_Driver_Disable,
    ROM_API_INDEX_GLB_IR_LED_Driver_Output_Enable,
    ROM_API_INDEX_GLB_IR_LED_Driver_Output_Disable,
    ROM_API_INDEX_GLB_IR_LED_Driver_Ibias,
    ROM_API_INDEX_GLB_GPIO_Init,
    ROM_API_INDEX_GLB_GPIO_Func_Init,
    ROM_API_INDEX_GLB_GPIO_OUTPUT_Mode_Set,
    ROM_API_INDEX_GLB_GPIO_INPUT_Enable,
    ROM_API_INDEX_GLB_GPIO_INPUT_Disable,
    ROM_API_INDEX_GLB_GPIO_OUTPUT_Enable,
    ROM_API_INDEX_GLB_GPIO_OUTPUT_Disable,
    ROM_API_INDEX_GLB_GPIO_Set_HZ,
    ROM_API_INDEX_GLB_GPIO_Get_Fun,
    ROM_API_INDEX_GLB_GPIO_Write,
    ROM_API_INDEX_GLB_GPIO_Read,
    ROM_API_INDEX_GLB_GPIO_Set,
    ROM_API_INDEX_GLB_GPIO_Clr,
    ROM_API_INDEX_GLB_GPIO_IntMask,
    ROM_API_INDEX_GLB_Clr_GPIO_IntStatus,
    ROM_API_INDEX_GLB_Get_GPIO_IntStatus,
    ROM_API_INDEX_GLB_GPIO_Int_Init,

    ROM_API_INDEX_HBN_Mode_Enter,
    ROM_API_INDEX_HBN_GPIO_Wakeup_Set,
    ROM_API_INDEX_HBN_Power_Down_Flash,
    ROM_API_INDEX_HBN_Enable,
    ROM_API_INDEX_HBN_Reset,
    ROM_API_INDEX_HBN_App_Reset,
    ROM_API_INDEX_HBN_Disable,
    ROM_API_INDEX_HBN_Get_BOR_OUT_State,
    ROM_API_INDEX_HBN_Set_BOR_Config,
    ROM_API_INDEX_HBN_Set_Ldo11_Aon_Vout,
    ROM_API_INDEX_HBN_Set_Ldo11_Soc_Vout,
    ROM_API_INDEX_HBN_Set_Ldo11_All_Vout,
    ROM_API_INDEX_HBN_32K_Sel,
    ROM_API_INDEX_HBN_Set_UART_CLK_Sel,
    ROM_API_INDEX_HBN_Set_XCLK_CLK_Sel,
    ROM_API_INDEX_HBN_Set_ROOT_CLK_Sel,
    ROM_API_INDEX_HBN_Set_HRAM_slp,
    ROM_API_INDEX_HBN_Set_HRAM_Ret,
    ROM_API_INDEX_HBN_Power_On_Xtal_32K,
    ROM_API_INDEX_HBN_Power_Off_Xtal_32K,
    ROM_API_INDEX_HBN_Power_On_RC32K,
    ROM_API_INDEX_HBN_Power_Off_RC32K,
    ROM_API_INDEX_HBN_Trim_RC32K,
    ROM_API_INDEX_HBN_Get_Status_Flag,
    ROM_API_INDEX_HBN_Set_Status_Flag,
    ROM_API_INDEX_HBN_Get_Wakeup_Addr,
    ROM_API_INDEX_HBN_Set_Wakeup_Addr,
    ROM_API_INDEX_HBN_Get_User_Boot_Config,
    ROM_API_INDEX_HBN_Set_User_Boot_Config,
    ROM_API_INDEX_HBN_Clear_RTC_Counter,
    ROM_API_INDEX_HBN_Enable_RTC_Counter,
    ROM_API_INDEX_HBN_Set_RTC_Timer,
    ROM_API_INDEX_HBN_Get_RTC_Timer_Val,
    ROM_API_INDEX_HBN_Clear_RTC_INT,
    ROM_API_INDEX_HBN_GPIO_INT_Enable,
    ROM_API_INDEX_HBN_GPIO_INT_Disable,
    ROM_API_INDEX_HBN_Get_INT_State,
    ROM_API_INDEX_HBN_Get_Pin_Wakeup_Mode,
    ROM_API_INDEX_HBN_Clear_IRQ,
    ROM_API_INDEX_HBN_Hw_Pu_Pd_Cfg,
    ROM_API_INDEX_HBN_Comm_Pad_Wakeup_En_Cfg,
    ROM_API_INDEX_HBN_Aon_Pad_IeSmt_Cfg,
    ROM_API_INDEX_HBN_Pin_WakeUp_Mask,
    ROM_API_INDEX_HBN_Enable_AComp0_IRQ,
    ROM_API_INDEX_HBN_Disable_AComp0_IRQ,
    ROM_API_INDEX_HBN_Enable_AComp1_IRQ,
    ROM_API_INDEX_HBN_Disable_AComp1_IRQ,
    ROM_API_INDEX_HBN_Enable_BOR_IRQ,
    ROM_API_INDEX_HBN_Disable_BOR_IRQ,
    ROM_API_INDEX_HBN_Get_Reset_Event,
    ROM_API_INDEX_HBN_Clear_Reset_Event,
    ROM_API_INDEX_HBN_GPIO_Dbg_Pull_Cfg,
    ROM_API_INDEX_HBN_Set_BOR_Cfg,

    ROM_API_INDEX_L1C_Cache_Write_Set,
    ROM_API_INDEX_L1C_Cache_Enable_Set,
    ROM_API_INDEX_L1C_Cache_Flush,
    ROM_API_INDEX_L1C_Cache_Hit_Count_Get,
    ROM_API_INDEX_L1C_Cache_Miss_Count_Get,
    ROM_API_INDEX_L1C_Cache_Read_Disable,
    ROM_API_INDEX_L1C_Set_Wrap,
    ROM_API_INDEX_L1C_Set_Way_Disable,
    ROM_API_INDEX_L1C_IROM_2T_Access_Set,
    ROM_API_INDEX_L1C_BMX_Init,
    ROM_API_INDEX_L1C_BMX_Addr_Monitor_Enable,
    ROM_API_INDEX_L1C_BMX_Addr_Monitor_Disable,
    ROM_API_INDEX_L1C_BMX_BusErrResponse_Enable,
    ROM_API_INDEX_L1C_BMX_BusErrResponse_Disable,
    ROM_API_INDEX_L1C_BMX_Get_Status,
    ROM_API_INDEX_L1C_BMX_Get_Err_Addr,

    ROM_API_INDEX_PDS_Set_GPIO_Pad_Cfg,
    ROM_API_INDEX_PDS_GPIO_Write,
    ROM_API_INDEX_PDS_Set_GPIO_Pad_IntMask,
    ROM_API_INDEX_PDS_Set_GPIO_Pad_IntMode,
    ROM_API_INDEX_PDS_Set_GPIO_Pad_IntClr,
    ROM_API_INDEX_PDS_Set_All_GPIO_IntClear,
    ROM_API_INDEX_PDS_Get_GPIO_Pad_IntStatus,
    ROM_API_INDEX_PDS_Disable_GPIO_Keep,
    ROM_API_INDEX_PDS_Enable,
    ROM_API_INDEX_PDS_Force_Config,
    ROM_API_INDEX_PDS_RAM_Config,
    ROM_API_INDEX_PDS_Default_Level_Config,
    ROM_API_INDEX_PDS_Wakeup_Src_En,
    ROM_API_INDEX_PDS_Get_Wakeup_Src,
    ROM_API_INDEX_PDS_IntMask,
    ROM_API_INDEX_PDS_Get_IntStatus,
    ROM_API_INDEX_PDS_IntClear,
    ROM_API_INDEX_PDS_Get_PdsRfStstus,
    ROM_API_INDEX_PDS_Get_PdsStstus,
    ROM_API_INDEX_PDS_Clear_Reset_Event,
    ROM_API_INDEX_PDS_Get_Reset_Event,
    ROM_API_INDEX_PDS_Auto_Enable,
    ROM_API_INDEX_PDS_Manual_Force_Turn_Off,
    ROM_API_INDEX_PDS_Manual_Force_Turn_On,
    ROM_API_INDEX_PDS_Set_KYD_Matrix_Size,
    ROM_API_INDEX_PDS_Set_KYD_Col_Value,
    ROM_API_INDEX_PDS_Set_KYD_Row_Pull,
    ROM_API_INDEX_PDS_Set_KYD_Wakeup_En,

    ROM_API_INDEX_SF_Cfg_Init_Internal_Flash_Gpio,
    ROM_API_INDEX_SF_Cfg_Init_Ext_Flash_Gpio,
    ROM_API_INDEX_SF_Cfg_Deinit_Ext_Flash_Gpio,
    ROM_API_INDEX_SF_Cfg_Get_Flash_Cfg_Need_Lock,
    ROM_API_INDEX_SF_Cfg_Init_Flash_Gpio,
    ROM_API_INDEX_SF_Cfg_Flash_Identify,
    ROM_API_INDEX_SF_Ctrl_Enable,
    ROM_API_INDEX_SF_Ctrl_Psram_Init,
    ROM_API_INDEX_SF_Ctrl_Get_Clock_Delay,
    ROM_API_INDEX_SF_Ctrl_Set_Clock_Delay,
    ROM_API_INDEX_SF_Ctrl_Cmds_Set,
    ROM_API_INDEX_SF_Ctrl_Burst_Toggle_Set,
    ROM_API_INDEX_SF_Ctrl_Select_Pad,
    ROM_API_INDEX_SF_Ctrl_Select_Bank,
    ROM_API_INDEX_SF_Ctrl_Set_Owner,
    ROM_API_INDEX_SF_Ctrl_Disable,
    ROM_API_INDEX_SF_Ctrl_AES_Enable_BE,
    ROM_API_INDEX_SF_Ctrl_AES_Enable_LE,
    ROM_API_INDEX_SF_Ctrl_AES_Set_Region,
    ROM_API_INDEX_SF_Ctrl_AES_Set_Key,
    ROM_API_INDEX_SF_Ctrl_AES_Set_Key_BE,
    ROM_API_INDEX_SF_Ctrl_AES_Set_IV,
    ROM_API_INDEX_SF_Ctrl_AES_Set_IV_BE,
    ROM_API_INDEX_SF_Ctrl_AES_Enable,
    ROM_API_INDEX_SF_Ctrl_AES_Disable,
    ROM_API_INDEX_SF_Ctrl_Is_AES_Enable,
    ROM_API_INDEX_SF_Ctrl_Set_Flash_Image_Offset,
    ROM_API_INDEX_SF_Ctrl_Get_Flash_Image_Offset,
    ROM_API_INDEX_SF_Ctrl_SendCmd,
    ROM_API_INDEX_SF_Ctrl_Flash_Read_Icache_Set,
    ROM_API_INDEX_SF_Ctrl_Psram_Write_Icache_Set,
    ROM_API_INDEX_SF_Ctrl_Psram_Read_Icache_Set,
    ROM_API_INDEX_SF_Ctrl_GetBusyState,

    ROM_API_INDEX_SFlash_Init,
    ROM_API_INDEX_SFlash_SetSPIMode,
    ROM_API_INDEX_SFlash_Read_Reg,
    ROM_API_INDEX_SFlash_Write_Reg,
    ROM_API_INDEX_SFlash_Read_Reg_With_Cmd,
    ROM_API_INDEX_SFlash_Write_Reg_With_Cmd,
    ROM_API_INDEX_SFlash_Clear_Status_Register,
    ROM_API_INDEX_SFlash_Busy,
    ROM_API_INDEX_SFlash_Write_Enable,
    ROM_API_INDEX_SFlash_Qspi_Enable,
    ROM_API_INDEX_SFlash_Volatile_Reg_Write_Enable,
    ROM_API_INDEX_SFlash_Chip_Erase,
    ROM_API_INDEX_SFlash_Sector_Erase,
    ROM_API_INDEX_SFlash_Blk32_Erase,
    ROM_API_INDEX_SFlash_Blk64_Erase,
    ROM_API_INDEX_SFlash_Erase,
    ROM_API_INDEX_SFlash_Program,
    ROM_API_INDEX_SFlash_GetUniqueId,
    ROM_API_INDEX_SFlash_GetJedecId,
    ROM_API_INDEX_SFlash_GetDeviceId,
    ROM_API_INDEX_SFlash_Powerdown,
    ROM_API_INDEX_SFlash_Releae_Powerdown,
    ROM_API_INDEX_SFlash_Restore_From_Powerdown,
    ROM_API_INDEX_SFlash_SetBurstWrap,
    ROM_API_INDEX_SFlash_DisableBurstWrap,
    ROM_API_INDEX_SFlash_Software_Reset,
    ROM_API_INDEX_SFlash_Reset_Continue_Read,
    ROM_API_INDEX_SFlash_Set_IDbus_Cfg,
    ROM_API_INDEX_SFlash_IDbus_Read_Enable,
    ROM_API_INDEX_SFlash_Cache_Read_Enable,
    ROM_API_INDEX_SFlash_Cache_Read_Disable,
    ROM_API_INDEX_SFlash_Read,

    ROM_API_INDEX_UART_SetBaudRate,
    ROM_API_INDEX_UART_Init,
    ROM_API_INDEX_UART_DeInit,
    ROM_API_INDEX_UART_FifoConfig,
    ROM_API_INDEX_UART_Enable,
    ROM_API_INDEX_UART_Disable,
    ROM_API_INDEX_UART_SetTxDataLength,
    ROM_API_INDEX_UART_SetRxDataLength,
    ROM_API_INDEX_UART_SetRxTimeoutValue,
    ROM_API_INDEX_UART_SetRxByteCount,
    ROM_API_INDEX_UART_SetDeglitchCount,
    ROM_API_INDEX_UART_ApplyAbrResult,
    ROM_API_INDEX_UART_SetRtsValue,
    ROM_API_INDEX_UART_ClrRtsValue,
    ROM_API_INDEX_UART_SetTxValue,
    ROM_API_INDEX_UART_ClrTxValue,
    ROM_API_INDEX_UART_TxFreeRun,
    ROM_API_INDEX_UART_AutoBaudDetection,
    ROM_API_INDEX_UART_SetAllowableError0X55,
    ROM_API_INDEX_UART_GetBitWidth0X55,
    ROM_API_INDEX_UART_SetRS485,
    ROM_API_INDEX_UART_TxFifoClear,
    ROM_API_INDEX_UART_RxFifoClear,
    ROM_API_INDEX_UART_IntMask,
    ROM_API_INDEX_UART_IntClear,
    ROM_API_INDEX_UART_SendData,
    ROM_API_INDEX_UART_SendDataBlock,
    ROM_API_INDEX_UART_ReceiveData,
    ROM_API_INDEX_UART_GetAutoBaudCount,
    ROM_API_INDEX_UART_GetRxByteCount,
    ROM_API_INDEX_UART_GetTxFifoCount,
    ROM_API_INDEX_UART_GetRxFifoCount,
    ROM_API_INDEX_UART_GetIntStatus,
    ROM_API_INDEX_UART_GetTxBusBusyStatus,
    ROM_API_INDEX_UART_GetRxBusBusyStatus,
    ROM_API_INDEX_UART_GetOverflowStatus,

    ROM_API_INDEX_XIP_SFlash_Opt_Enter,
    ROM_API_INDEX_XIP_SFlash_Opt_Exit,
    ROM_API_INDEX_XIP_SFlash_State_Save,
    ROM_API_INDEX_XIP_SFlash_State_Restore,
    ROM_API_INDEX_XIP_SFlash_Erase_Need_Lock,
    ROM_API_INDEX_XIP_SFlash_Write_Need_Lock,
    ROM_API_INDEX_XIP_SFlash_Read_Need_Lock,
    ROM_API_INDEX_XIP_SFlash_GetJedecId_Need_Lock,
    ROM_API_INDEX_XIP_SFlash_GetDeviceId_Need_Lock,
    ROM_API_INDEX_XIP_SFlash_GetUniqueId_Need_Lock,
    ROM_API_INDEX_XIP_SFlash_Read_Via_Cache_Need_Lock,
    ROM_API_INDEX_XIP_SFlash_Clear_Status_Register_Need_Lock,

    ROM_API_INDEX_IR_TxInit,
    ROM_API_INDEX_IR_TxPulseWidthConfig,
    ROM_API_INDEX_IR_FifoConfig,
    ROM_API_INDEX_IR_DeInit,
    ROM_API_INDEX_IR_Enable,
    ROM_API_INDEX_IR_Disable,
    ROM_API_INDEX_IR_TxSWM,
    ROM_API_INDEX_IR_TxFifoClear,
    ROM_API_INDEX_IR_SendData,
    ROM_API_INDEX_IR_SWMSendData,
    ROM_API_INDEX_IR_SendCommand,
    ROM_API_INDEX_IR_SWMSendCommand,
    ROM_API_INDEX_IR_SendNEC,
    ROM_API_INDEX_IR_IntMask,
    ROM_API_INDEX_IR_ClrIntStatus,
    ROM_API_INDEX_IR_GetIntStatus,
    ROM_API_INDEX_IR_GetFifoStatus,
    ROM_API_INDEX_IR_GetTxFifoCount,
    ROM_API_INDEX_IR_LEDInit,
    ROM_API_INDEX_IR_LEDSend,

    ROM_API_INDEX_KYS_Init,
    ROM_API_INDEX_KYS_Enable,
    ROM_API_INDEX_KYS_Disable,
    ROM_API_INDEX_KYS_IntMask,
    ROM_API_INDEX_KYS_IntClear,
    ROM_API_INDEX_KYS_GetIntStatus,
    ROM_API_INDEX_KYS_Get_FIFO_Idx,
    ROM_API_INDEX_KYS_ReadKeyfifo,

    ROM_API_INDEX_Psram_Init,
    ROM_API_INDEX_Psram_ReadReg,
    ROM_API_INDEX_Psram_WriteReg,
    ROM_API_INDEX_Psram_SetDriveStrength,
    ROM_API_INDEX_Psram_SetBurstWrap,
    ROM_API_INDEX_Psram_ReadId,
    ROM_API_INDEX_Psram_EnterQuadMode,
    ROM_API_INDEX_Psram_ExitQuadMode,
    ROM_API_INDEX_Psram_ToggleBurstLength,
    ROM_API_INDEX_Psram_SoftwareReset,
    ROM_API_INDEX_Psram_Set_IDbus_Cfg,
    ROM_API_INDEX_Psram_Cache_Write_Set,
    ROM_API_INDEX_Psram_Write,
    ROM_API_INDEX_Psram_Read,

    ROM_API_INDEX_TIMER_GetCompValue,
    ROM_API_INDEX_TIMER_SetCompValue,
    ROM_API_INDEX_TIMER_CompValueEffectImmediately,
    ROM_API_INDEX_TIMER_GetCounterValue,
    ROM_API_INDEX_TIMER_ResetCounterValue,
    ROM_API_INDEX_TIMER_GetMatchStatus,
    ROM_API_INDEX_TIMER_GetPreloadValue,
    ROM_API_INDEX_TIMER_SetPreloadValue,
    ROM_API_INDEX_TIMER_SetPreloadTrigSrc,
    ROM_API_INDEX_TIMER_SetCountMode,
    ROM_API_INDEX_TIMER_ClearIntStatus,
    ROM_API_INDEX_TIMER_Init,
    ROM_API_INDEX_TIMER_DeInit,
    ROM_API_INDEX_TIMER_Enable,
    ROM_API_INDEX_TIMER_Disable,
    ROM_API_INDEX_TIMER_IntMask,
    ROM_API_INDEX_TIMER_GPIOSetPolarity,
    ROM_API_INDEX_TIMER_CH0_SetMeasurePulseWidth,
    ROM_API_INDEX_TIMER_CH0_GetMeasurePulseWidth,
    ROM_API_INDEX_TIMER_ForceClockDivision,

    ROM_API_INDEX_WDT_Set_Clock,
    ROM_API_INDEX_WDT_GetMatchValue,
    ROM_API_INDEX_WDT_SetCompValue,
    ROM_API_INDEX_WDT_CompValueEffectImmediately,
    ROM_API_INDEX_WDT_GetCounterValue,
    ROM_API_INDEX_WDT_ResetCounterValue,
    ROM_API_INDEX_WDT_GetResetStatus,
    ROM_API_INDEX_WDT_ClearResetStatus,
    ROM_API_INDEX_WDT_Enable,
    ROM_API_INDEX_WDT_Disable,
    ROM_API_INDEX_WDT_ForceClockDivision,
    ROM_API_INDEX_WDT_IntMask,
    ROM_API_INDEX_WDT_GPIOSetPolarity,

    ROM_API_INDEX_arch_memcpy,
    ROM_API_INDEX_arch_memcpy4,
    ROM_API_INDEX_arch_memcpy_fast,
    ROM_API_INDEX_arch_memset,
    ROM_API_INDEX_arch_memset4,
    ROM_API_INDEX_arch_memcmp,

    ROM_API_INDEX_memcopy_to_fifo,

    ROM_API_INDEX_fifocopy_to_mem,

    ROM_API_INDEX_BFLB_Soft_CRC32_Ex,
    ROM_API_INDEX_BFLB_Soft_CRC32,

    ROM_API_INDEX_FUNC_EMPTY_START,

    ROM_API_INDEX_FUNC_EMPTY_END = ROMAPI_INDEX_MAX

} ROM_API_INDEX_e;


#define ROM_APITABLE            ((uint32_t *)0x21010800)

typedef struct
{
    uint8_t gpioPin;
    uint8_t gpioFun;
    uint8_t gpioMode;
    uint8_t pullType;
    uint8_t drive;
    uint8_t smtCtrl;
} GLB_GPIO_Cfg_Type;

typedef enum {
    GLB_GPIO_PIN_0 = 0,
    GLB_GPIO_PIN_1,
    GLB_GPIO_PIN_2,
    GLB_GPIO_PIN_3,
    GLB_GPIO_PIN_4,
    GLB_GPIO_PIN_5,
    GLB_GPIO_PIN_6,
    GLB_GPIO_PIN_7,
    GLB_GPIO_PIN_8,
    GLB_GPIO_PIN_9,
    GLB_GPIO_PIN_10,
    GLB_GPIO_PIN_11,
    GLB_GPIO_PIN_12,
    GLB_GPIO_PIN_13,
    GLB_GPIO_PIN_14,
    GLB_GPIO_PIN_15,
    GLB_GPIO_PIN_16,
    GLB_GPIO_PIN_17,
    GLB_GPIO_PIN_18,
    GLB_GPIO_PIN_19,
    GLB_GPIO_PIN_20,
    GLB_GPIO_PIN_21,
    GLB_GPIO_PIN_22,
    GLB_GPIO_PIN_23,
    GLB_GPIO_PIN_24,
    GLB_GPIO_PIN_25,
    GLB_GPIO_PIN_26,
    GLB_GPIO_PIN_27,
    GLB_GPIO_PIN_28,
    GLB_GPIO_PIN_29,
    GLB_GPIO_PIN_30,
    GLB_GPIO_PIN_31,
    GLB_GPIO_PIN_MAX,
} GLB_GPIO_Type;

typedef enum {
    SUCCESS = 0,
    ERROR = 1,
    TIMEOUT = 2,
    INVALID = 3, /* invalid arguments */
    NORESC = 4   /* no resource or resource temperary unavailable */
} BL_Err_Type;

#define RomDriver_BL702L_Delay_MS \
    ((void (*)(uint32_t cnt))ROM_APITABLE[ROM_API_INDEX_BL702L_Delay_MS])
#define RomDriver_GLB_GPIO_Init \
    ((BL_Err_Type(*)(GLB_GPIO_Cfg_Type * cfg)) ROM_APITABLE[ROM_API_INDEX_GLB_GPIO_Init])
#define RomDriver_GLB_GPIO_OUTPUT_Enable \
    ((BL_Err_Type(*)(GLB_GPIO_Type gpioPin))ROM_APITABLE[ROM_API_INDEX_GLB_GPIO_OUTPUT_Enable])
#define RomDriver_GLB_GPIO_OUTPUT_Disable \
    ((BL_Err_Type(*)(GLB_GPIO_Type gpioPin))ROM_APITABLE[ROM_API_INDEX_GLB_GPIO_OUTPUT_Disable])

#define RomDriver_GLB_GPIO_Write                          \
    ((BL_Err_Type (*) (GLB_GPIO_Type gpioPin, uint32_t val))ROM_APITABLE[ROM_API_INDEX_GLB_GPIO_Write])

#endif